import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Blue Accent Chair",
    description: "A comfortable blue accent chair with wooden legs, perfect for any living room.",
    price: 299.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "chair",
    featured: true,
    inStock: true,
    colors: ["blue", "gray", "beige"],
  },
  {
    id: "2",
    name: "Teal Armchair",
    description: "Luxurious teal armchair with tufted back and solid wood legs.",
    price: 349.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "chair",
    featured: true,
    inStock: true,
    colors: ["teal", "navy", "gray"],
  },
  {
    id: "3",
    name: "Modern Sofa",
    description: "Three-seater modern sofa with blue upholstery and wooden legs.",
    price: 899.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "sofa",
    featured: true,
    inStock: true,
    colors: ["blue", "gray", "beige"],
  },
  {
    id: "4",
    name: "Pink Accent Chair",
    description: "Stylish pink accent chair with curved back and gold-finished metal legs.",
    price: 279.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "chair",
    featured: false,
    inStock: true,
    colors: ["pink", "cream"],
  },
  {
    id: "5",
    name: "Beige Lounge Chair",
    description: "Comfortable beige lounge chair with ottoman, perfect for relaxing.",
    price: 449.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "chair",
    featured: false,
    inStock: true,
    colors: ["beige", "brown", "gray"],
  },
  {
    id: "6",
    name: "Blue Loveseat",
    description: "Compact blue loveseat, ideal for small spaces and apartments.",
    price: 599.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "sofa",
    featured: false,
    inStock: true,
    colors: ["blue", "navy"],
  },
  {
    id: "7",
    name: "White Dining Chair",
    description: "Set of white dining chairs with wooden legs, modern and minimalist design.",
    price: 149.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "chair",
    featured: false,
    inStock: true,
    colors: ["white", "black", "natural"],
  },
  {
    id: "8",
    name: "Gray Sectional Sofa",
    description: "Large gray sectional sofa with chaise lounge, perfect for family rooms.",
    price: 1299.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "sofa",
    featured: true,
    discount: 15,
    inStock: true,
    colors: ["gray", "charcoal", "light gray"],
  },
]

export const categories = [
  { id: "all", name: "All products" },
  { id: "chair", name: "Chairs" },
  { id: "sofa", name: "Sofas" },
  { id: "table", name: "Tables" },
  { id: "bedroom", name: "Bedroom" },
  { id: "office", name: "Home Office" },
]

